baseURL = "https://你的用户名.github.io/"
languageCode = "zh-cn"
title = "我的博客"
theme = "FixIt"

[params.author]
  name = "张三"
  link = "https://github.com/zhangsan"

[params]
  description = "这是我的技术博客"
  enableAutoDarkMode = true
  defaultTheme = "auto"
  dateFormat = "2006-01-02"

[pagination]
  pagerSize = 10

